import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode, Navigation, Thumbs, Autoplay } from "swiper/modules";
import { RiPlayFill } from "react-icons/ri";
import { GoSun } from "react-icons/go";
import { PiMoonLight } from "react-icons/pi";
import { IMAGE_URL } from "@/const";
const SwiperSlider = ({ moviesData, thumbsSwiper, setThumbsSwiper, theme, handleTheme, isMobile, getGenreNames }) => {
    return (_jsxs(_Fragment, { children: [_jsx(Swiper, { spaceBetween: 0, centeredSlides: true, autoplay: {
                    delay: 3500,
                    disableOnInteraction: true,
                }, thumbs: { swiper: thumbsSwiper }, modules: [FreeMode, Navigation, Thumbs, Autoplay], className: "mySwiper2 md:rounded-xl overflow-hidden", children: moviesData.map((movie) => (_jsxs(SwiperSlide, { className: "relative", children: [_jsx("img", { className: "w-full h-full object-contain", src: IMAGE_URL + movie.backdrop_path, loading: "lazy", alt: movie.title }), _jsx("button", { onClick: handleTheme, className: "md:hidden absolute z-20 top-4 right-4 flex items-center justify-center gap-2 backdrop-blur-md bg-bg-dark-900/20 light:bg-bg-light-900/40 duration-150 ease-out size-9 rounded-xl", children: theme ? (_jsx(PiMoonLight, { className: "text-xl" })) : (_jsx(GoSun, { className: "text-xl" })) }), _jsxs("div", { className: "absolute right-1/2 bottom-7 sm:bottom-6 translate-x-1/2 flex flex-col gap-4 w-full", children: [_jsx("h1", { className: "text-2xl md:text-3xl lg:text-[32px] w-[90%] sm:w-[80%] mx-auto md:w-full text-text-dark-100 tracking-wide text-shadow-[2px_2px_4px_rgba(0,0,0,0.5)]", children: movie.title }), _jsxs("div", { className: "flex items-center justify-center gap-2 text-sm tracking-wide text-text-dark-100", children: [_jsx("p", { className: "text-shadow-[2px_2px_4px_rgba(0,0,0,0.5)]", children: movie.release_date.slice(0, 4) }), _jsx("span", { className: "text-xs leading-4", children: "\u2022" }), _jsx("p", { className: "line-clamp-1 flex items-center gap-1 flex-wrap", children: getGenreNames(movie.genre_ids.slice(0, 1)).map((genre, index) => (_jsx("span", { className: "text-shadow-[2px_2px_4px_rgba(0,0,0,0.5)]", children: genre }, index))) }), _jsx("span", { className: "text-xs leading-4", children: "\u2022" }), _jsx("p", { className: "uppercase text-shadow-[2px_2px_4px_rgba(0,0,0,0.5)]", children: movie.original_language }), _jsx("span", { className: "text-xs leading-4", children: "\u2022" }), _jsx("p", { className: "text-shadow-[2px_2px_4px_rgba(0,0,0,0.5)]", children: movie.adult ? "18+" : "6+" })] }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("button", { className: "w-[82%] min-[450px]:w-[380px] md:w-[380px] h-12 sm:h-[52px] flex items-center justify-center gap-[7px] bg-text-dark-100 rounded-xl text-primary", children: [_jsx(RiPlayFill, { className: "text-2xl" }), _jsx("span", { className: "tracking-wide", children: "Watch" })] }) })] })] }, movie.id))) }), !isMobile && (_jsx(Swiper, { onSwiper: setThumbsSwiper, spaceBetween: 4, slidesPerView: 4, freeMode: true, watchSlidesProgress: true, modules: [FreeMode, Navigation, Thumbs], className: "mySwiper select-none", children: moviesData.map((movie) => (_jsx(SwiperSlide, { className: "overflow-hidden rounded-xl cursor-pointer", children: _jsx("img", { className: "w-full h-full object-contain hover:scale-105 duration-150 ease-out", src: IMAGE_URL + movie.backdrop_path, loading: "lazy", alt: movie.title }) }, movie.id))) }))] }));
};
export default SwiperSlider;
